### ISSUE TITLE
Issue in README

### ISSUE THREAD

**Issue by dhruvdabhi101** [AbhimanyuAjudiya/solana-blog#1]
https://github.com/AbhimanyuAjudiya/solana-blog/blob/2402c3caacbe7a87c38f767d327dfc7c2ceaf79a/README.md?plain=1#L82

Maybe there is a mistake in wallet naming. You have to connect Phantom Wallet since you are using Solana right here.

**Comment by AbhimanyuAjudiya** [comment]
> https://github.com/AbhimanyuAjudiya/solana-blog/blob/2402c3caacbe7a87c38f767d327dfc7c2ceaf79a/README.md?plain=1#L82
> 
> 
> 
> Maybe there is a mistake in wallet naming. You have to connect Phantom Wallet since you are using Solana right here. 

By mistake I wrote metamask, now i have changed it to Phantom.
